# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{yuzu}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["William Martin"]
  s.date = %q{2013-02-12}
  s.default_executable = %q{yuzu}
  s.description = %q{Yuzu is a blog-aware, static-website (and PDF) generator that converts a folder of text files and images into multiple forms and publishes them to an FTP server, file system, or Amazon Simple Storage Service (S3). It is extensible and designed to function with minimal setup.}
  s.email = %q{william.martin@anomalus.com}
  s.executables = ["yuzu"]
  s.extra_rdoc_files = [
    "ChangeLog.md",
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".yardopts",
    "ChangeLog.md",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "bin/yuzu",
    "docs/About.md",
    "docs/GettingStarted.md",
    "docs/Reference.md",
    "lib/helpers/object.rb",
    "lib/helpers/path.rb",
    "lib/helpers/string.rb",
    "lib/helpers/system_checks.rb",
    "lib/helpers/url.rb",
    "lib/html/base.rb",
    "lib/uploader/base.rb",
    "lib/uploader/config.rb",
    "lib/uploader/filesystem_service.rb",
    "lib/uploader/ftp_service.rb",
    "lib/uploader/s3_service.rb",
    "lib/uploader/service.rb",
    "lib/uploader/suppressor.rb",
    "lib/yuzu.rb",
    "lib/yuzu/argparse.rb",
    "lib/yuzu/command.rb",
    "lib/yuzu/commands/base.rb",
    "lib/yuzu/commands/create.rb",
    "lib/yuzu/commands/generate.rb",
    "lib/yuzu/commands/help.rb",
    "lib/yuzu/commands/preview.rb",
    "lib/yuzu/commands/publish.rb",
    "lib/yuzu/commands/stage.rb",
    "lib/yuzu/commands/watch.rb",
    "lib/yuzu/content/blog_post.rb",
    "lib/yuzu/content/sample_project.rb",
    "lib/yuzu/core/config.rb",
    "lib/yuzu/core/layout.rb",
    "lib/yuzu/core/paginated_file.rb",
    "lib/yuzu/core/registrar.rb",
    "lib/yuzu/core/siteroot.rb",
    "lib/yuzu/core/template.rb",
    "lib/yuzu/core/updater.rb",
    "lib/yuzu/core/visitor.rb",
    "lib/yuzu/core/website_base.rb",
    "lib/yuzu/core/website_file.rb",
    "lib/yuzu/core/website_folder.rb",
    "lib/yuzu/filters/base.rb",
    "lib/yuzu/filters/catalog.rb",
    "lib/yuzu/filters/categories.rb",
    "lib/yuzu/filters/currentpath.rb",
    "lib/yuzu/filters/description.rb",
    "lib/yuzu/filters/extension.rb",
    "lib/yuzu/filters/images.rb",
    "lib/yuzu/filters/linkroot.rb",
    "lib/yuzu/filters/post_date.rb",
    "lib/yuzu/filters/post_title.rb",
    "lib/yuzu/filters/post_title_removed.rb",
    "lib/yuzu/filters/sidebar.rb",
    "lib/yuzu/filters/template.rb",
    "lib/yuzu/generators/base.rb",
    "lib/yuzu/generators/category_folders.rb",
    "lib/yuzu/generators/index.rb",
    "lib/yuzu/generators/paginate.rb",
    "lib/yuzu/postprocessors/all_categories.rb",
    "lib/yuzu/postprocessors/base.rb",
    "lib/yuzu/postprocessors/contents_without_first_paragraph.rb",
    "lib/yuzu/postprocessors/excerpt.rb",
    "lib/yuzu/postprocessors/first_paragraph.rb",
    "lib/yuzu/postprocessors/pagination.rb",
    "lib/yuzu/postprocessors/recent_posts.rb",
    "lib/yuzu/postprocessors/thumbnails.rb",
    "lib/yuzu/preprocessors/base.rb",
    "lib/yuzu/preprocessors/insert_contents.rb",
    "lib/yuzu/renderers/base.rb",
    "lib/yuzu/renderers/breadcrumb.rb",
    "lib/yuzu/renderers/gallery.rb",
    "lib/yuzu/renderers/title.rb",
    "lib/yuzu/translators/base.rb",
    "lib/yuzu/translators/markdown.rb",
    "lib/yuzu/translators/plaintext.rb",
    "lib/yuzu/version.rb",
    "resources/config/compass.rb",
    "resources/config/yuzu.yml",
    "resources/git/post-commit",
    "resources/sample_content/introduction/_snippets/about_insert_contents.md",
    "resources/sample_content/introduction/about.md",
    "resources/sample_content/introduction/advanced-posts.md",
    "resources/sample_content/introduction/blog/autogenerated-index-files.md",
    "resources/sample_content/introduction/blog/blog-folder-is-special.md",
    "resources/sample_content/introduction/getting-started.md",
    "resources/sample_content/introduction/index.md",
    "resources/sample_content/introduction/sample-post.md",
    "resources/sample_projects.yml",
    "resources/themes/minimal/_sass/print.sass",
    "resources/themes/minimal/_sass/screen.sass",
    "resources/themes/minimal/_templates/_block.haml",
    "resources/themes/minimal/_templates/_blog.haml",
    "resources/themes/minimal/_templates/_footer.haml",
    "resources/themes/minimal/_templates/_gallery.haml",
    "resources/themes/minimal/_templates/_head.haml",
    "resources/themes/minimal/_templates/_header.haml",
    "resources/themes/minimal/_templates/_menu.haml",
    "resources/themes/minimal/_templates/blog.haml",
    "resources/themes/minimal/_templates/generic.haml",
    "resources/themes/minimal/_templates/home.haml",
    "resources/themes/minimal/_templates/index.haml",
    "resources/themes/minimal/css/print.css",
    "resources/themes/minimal/css/screen.css",
    "resources/themes/minimal/img/favicon.png",
    "resources/yard/default/fulldoc/html/css/common.css",
    "test/helper.rb",
    "test/test_yuzu.rb",
    "yuzu.gemspec"
  ]
  s.homepage = %q{http://github.com/awmartin/yuzu}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A blog-aware, static-website generator that converts a folder of text files and images into an HTML5 website.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<haml>, [">= 3.1.7"])
      s.add_runtime_dependency(%q<kramdown>, [">= 0.13.7"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.2.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0.8.3"])
      s.add_runtime_dependency(%q<kramdown>, [">= 0.13.7"])
      s.add_runtime_dependency(%q<haml>, [">= 3.1.1"])
    else
      s.add_dependency(%q<haml>, [">= 3.1.7"])
      s.add_dependency(%q<kramdown>, [">= 0.13.7"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.2.3"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0.8.3"])
      s.add_dependency(%q<kramdown>, [">= 0.13.7"])
      s.add_dependency(%q<haml>, [">= 3.1.1"])
    end
  else
    s.add_dependency(%q<haml>, [">= 3.1.7"])
    s.add_dependency(%q<kramdown>, [">= 0.13.7"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.2.3"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0.8.3"])
    s.add_dependency(%q<kramdown>, [">= 0.13.7"])
    s.add_dependency(%q<haml>, [">= 3.1.1"])
  end
end

